---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ${KUBE_NAMESPACE}
  annotations:
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
    deploy-timestamp: "${DEPLOY_TIMESTAMP}"
spec:
  serviceName: ${KUBE_NAMESPACE}
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ${KUBE_NAMESPACE}
  template:
    metadata:
      labels:
        app: ${KUBE_NAMESPACE}
      annotations:
        deploy-timestamp: "${DEPLOY_TIMESTAMP}"
        app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
        app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}  
    spec:
      #securityContext:
      #  fsGroup: 1000
      imagePullSecrets:
      - name: docker-secret
      automountServiceAccountToken: false
      containers:
      - name: ${KUBE_NAMESPACE}
        image: "${DEPLOY_IMAGE}"
        imagePullPolicy: Always                                                  
        ports:
        - containerPort: ${CONTAINER_PORT}
        volumeMounts:
          - name: ${KUBE_NAMESPACE}
            mountPath: /opt/data
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
            ephemeral-storage: 10Mi
          limits:
            cpu: 1
            memory: 1Gi
            ephemeral-storage: 128Mi
  volumeClaimTemplates:
  - metadata:
      name: ${KUBE_NAMESPACE}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-nfs-storage"
      resources:
        requests:
          storage: 1Gi
